dist: trusty
sudo: required
language: java
jdk:
- openjdk8
addons:
  apt:
    packages:
    - rpm
    - expect
env:
  global:
  - LC_ALL=C
  - secure: ZN+x3uHFU9zkmm+5pBdoblGnDOWduehzx38bn3oS/sgudryK3QAWniIJBuubN4APtZ3kh1mt0BP4p3xi8EsLHVBrM0UY4s9sJQMxt5cRW0JIwhvDaP4Z6wdWdQp1ubofKy+F7kA9ttWTzap9DVVsGDGD8cIbB4+4cgEaoAdKEcUbqGCgjdTp8vRpVpVSpfO7PFoBEh1beoDPr8iryOnw7TsgLKwwwkLdWojM9Int26t9ZcG3NJu1ijzjeI/l7uUQ+aGb+fcoG9KovYCGXxjjT5wzw07qNCEcpE9J67M4jvcTxKkCoS4+z/vUzycXs010yi5LQGdN1Y4pf4fKFkOBDkH1zrU94b2KNkcsCocC0gCW0qBw3VFBzJDuXok+Tuq5ol6gxooEVN1NvdfWhMsB37WLSFSdKVGeA3mp84m4/zK7cTHmEio4zUsr8+SJL/cYSN/DLqMMxPobRand80lGEaY9E1oG32r5QaPIGC7qCZRNDqkZJNyyGYx/Q4LQMNNMuohN9AJO+vT533Oa0Pixq0z45fupoEecXhF8L9oULooxLrsdcd1ajX87hlHdBmgH9nUnvuN+01lodJTl1jO1FMCYZaVV4mAndwivcJ4oZT0HFjRPHhKGNOlvRM9doSda4o1s82JGFAJBjgDRoIFJf3cWnXcfVm7YwUTvUtNQWO8=
  - secure: O3sqTT806pyvpLF2dyXxchXpkaHBC4eFKl5wllPmG4EZKkG/Ctqu6mhpmzSFmsoa4C9snxM/1diTSWMOE2UBdl8qYcruEUUSCS2gcSBaNvPgzEY8XbJtbtpRZ9xHjnrEojbUeXttRIix9fc3TfK9cm4vODkbg9y+2/pF3OM42G7pfxgL+e0i+zjhqlsTskK+zL4EUtJbYLvuggoS167oReG/jWllrrNQ0shALuuyingl4UYYYqCCjgTPpX+Il62uPNWgFoZyXC9VuOQO8i26/rj/ra2K7G3Zho20o2jFYA6DZd/pOH1HhkeyYxHL+hA3FWTy48hO4zoR+ZxaI+qV1FsheaAwZVWbb0dVdBgqBRig6si4sVb1+RYNtseyU545/773i8zP+QN+h/e3/lYZ3Ji+uPjXJBZPGsbH/dN8VtDOKpYF1Fl8qddxs+1lMcYzZe5mRswku1Ky03z8x3kl8CoO8t4GdL1L/YdgWrO54WwuRq42KBKDTbwdhSuvC741l2nluV5eBZgONWhfXHpzoqvDvuIV7bjApkElWTD1bjAXvWFwUV5OmVa5TY/I54kqE35+rlJmixWRLkLzBPLKTtCUXCsXSqFqkvzQ76yDfdAoB7cuAt8BOK/vjFvGpgW3N3SJ0wzi3MnXeNZxOSfqa3tGgTn4+80uW0HyO1U2djs=
  - secure: WRD2xln0AJ/viKMntTJoBZ7ae8uiKG7a3TgHamIIsK8YlnQFU+CGCLELCcz0Y2ef0aepb4mDLorb0o6yw2Z2olPILbDjZKBV1T4tPXzwKMM947wFg1zPPHTILP9OTEG7quXA4ahktNaVMZGAy2a720PtLx1lKXs9TvY1yhubs4fggM80o0wTlv+yjYOkH0q6NGv9O3FEQ+tA7JD5+5fEjeaCQSLDpV1vHi7mvx9IoZr446M8H+nTPuEGqvomG7J8wtMTfrpPZhA8sKPbUd9BUVjgK86NkfJFfelJCytOst1c0WdY/DlzaqJQqne5VSuAmHqyWyysC/W6Y+NFN318ZPA++XrghblRYiywWMmX4u3GyAbcxBr3woAankrlaTguWThu2tRfJXyD2/r2V7IdpPZKcJki+wmgLbTa1BaDXVUji743iCZLk8CqttMefC/J7kH9Cny6zx8hJc0O6zQvfGjNwRXWfx0En7BQz1MoQdlnnN2NeH+KcxPOOWClOewuW/iaE9eluYiKbwud0PO1s1rkHk6CYDA6zI2d+DQjmsDqtI/Ljo+yyb+5bsqpQ1GRZALx84oSvBKfU3E6VZ0wo6dCNfdyV99bdOYaYkdQFvs2DH7n7zA8amHZSYHKdFQbY+wvADeYNrswEZFgxVUyInDBXe39OhxKIb2OjWxMyXY=
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dskip.web.build=true -Dsource.skip=true -Dgpg.skip -B -V
script:
- mvn package -Dmaven.javadoc.skip=true -Dsource.skip=true -Dgpg.skip -B
after_success:
- openssl aes-256-cbc -K $encrypted_2eb549732242_key -iv $encrypted_2eb549732242_iv -in deployment/signingkey.asc.enc -out deployment/signingkey.asc -d
- gpg2 --import deployment/signingkey.asc
- gpg2 --allow-secret-key-import --import deployment/signingkey.asc
before_deploy:
- mvn jdeb:jdeb --settings deployment/settings.xml && export RELEASE_DEB_FILE=$(ls target/*.deb)
- mvn rpm:rpm --settings deployment/settings.xml && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
- rm -f target/original-*.jar
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: aeFzD3aVzXSdTPZniQCD1q46dDOzF5BZizRjiCOJAYK//EVrAJNxJqKSeC0PDoUHI+YBkIkXk8ejnnHz214IJVbdysUEAab6kEv4ECf5u8abxdyImZb1zD/aen4IMcLAaaVSRflF+zCJmEXISULHOUigvD3jYgYFmYx3rp4iB9tXB9j087uhDw9ww1YA5UVjVTZGAXlRYv/J/bqM32yryfKiyGIpf7Wqf8/Dnz7N4PoCBBfHxa20gvm9dwTVjSYy0719r8d501J0F0N1ZbODp8RmlR36S8Wz+0oO0+kqbNMcK/eiB2RScrdjZDStF+6FMzxwJDOoYejAAVHAJAgF4cpxXY7EmimHYpbJmdtDAmO2GLZgI8Uh9krqHAe92R2ZD7boyHi91zU7ybjJ67tQN/adc8Qw5aRvb80FZEIs22sOD/cKo0lYvkXlkW/eCiAPkTMiKOyT3YjapTkJj6BzcHXds3DeD75J2M3RldcKGpwzkcPtEOfkt1YXud0ThiE7HCZRJ5wU2W4l/PCC1XQQh8pV09Ixtwp+TYnska1KC7nELj+ZmRE2jhH2KURBNS5ELwlbe8XsBBwRPj4B3ZVTKkjxRw/B+AdpCNXvST/2d4Al9qpeTmH3oE27p+X+WY+2zpYkP//+blAPQaYKcgPSHUYQvmMhRbk+UgQOBayBIwM=
  file: 
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_DEB_FILE}"
  - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    repo: airbus-cyber/graylog-plugin-correlation-count
    jdk: openjdk8
    tags: true
after_deploy:
- echo "Deploying release to Maven Central"
- mvn clean deploy -DskipTests=true --settings deployment/settings.xml
