version: '3'
services:

  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: "mongo:4.2"
    container_name: mongo4
    networks:
      net:
        ipv4_address: 172.15.0.2

  # OpenSearch: https://opensearch.org/docs/1.3/install-and-configure/install-opensearch/docker/#sample-docker-composeyml
  opensearch:
    image: "opensearchproject/opensearch:1.3.9"
    container_name: opensearch1.3
    environment:
      - plugins.security.disabled=true
      - discovery.type=single-node
      - action.auto_create_index=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    networks:
      net:
        ipv4_address: 172.15.0.3

  # Graylog: https://hub.docker.com/r/graylog/graylog/ 
  graylog:
    image: "graylog/graylog:4.3"
    container_name: graylog
    links:
      - mongo:mongo
      - opensearch
    depends_on:
      - mongo
      - opensearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      net:
        ipv4_address: 172.15.0.4
    volumes:
     - ./graylog/config:/usr/share/graylog/data/config
     - ./graylog/plugin:/usr/share/graylog/plugin/

networks:
  net:
    ipam:
      driver: default
      config:
      - subnet: 172.15.0.0/16

