# sources of inspiration for this file
# * https://go2docs.graylog.org/5-1/downloading_and_installing_graylog/docker_installation.htm
# * https://github.com/Graylog2/docker-compose

services:

  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: "mongo:6.0"
    container_name: mongo

  # OpenSearch:
  # * https://hub.docker.com/r/opensearchproject/opensearch
  # * https://opensearch.org/docs/2.15/install-and-configure/install-opensearch/docker/#sample-docker-composeyml
  # * Bump 2.15.0 : https://graylog.org/post/announcing-graylog-v6-1/
  opensearch:
    image: "opensearchproject/opensearch:2.15.0"
    container_name: opensearch2.15
    environment:
      - plugins.security.disabled=true
      - discovery.type=single-node
      - action.auto_create_index=false
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=T3st-P@ssword!
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: "graylog/graylog:6.1.0"
    container_name: graylog
    links:
      - mongo:mongo
      - opensearch
    depends_on:
      - mongo
      - opensearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Raw/Plaintext TCP
      - 5555:5555
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    volumes:
     - ./graylog/config:/usr/share/graylog/data/config
     - ./graylog/plugin:/usr/share/graylog/plugin/
